export const IRRADIANCE_TEXTURE_WIDTH = 64;
export const IRRADIANCE_TEXTURE_HEIGHT = 16;
export const SCATTERING_TEXTURE_R_SIZE = 32;
export const SCATTERING_TEXTURE_MU_SIZE = 128;
export const SCATTERING_TEXTURE_MU_S_SIZE = 32;
export const SCATTERING_TEXTURE_NU_SIZE = 8;
export const SCATTERING_TEXTURE_WIDTH = SCATTERING_TEXTURE_NU_SIZE * SCATTERING_TEXTURE_MU_S_SIZE;
export const SCATTERING_TEXTURE_HEIGHT = SCATTERING_TEXTURE_MU_SIZE;
export const SCATTERING_TEXTURE_DEPTH = SCATTERING_TEXTURE_R_SIZE;
export const TRANSMITTANCE_TEXTURE_WIDTH = 256;
export const TRANSMITTANCE_TEXTURE_HEIGHT = 64;

export const METER_TO_LENGTH_UNIT = 1 / 1000;